#!/bin/bash

editor="nvim"
authenticator="doas"

file="$1"
directory=$(dirname $file)

auth () {
    echo You dont have write privileges for this file.
    echo Please enter your passwor to proceed:
    $authenticator $editor $file;
    exit 0
}

touchfile () {
    #sets directory to be the first existing parent directory of wanted file
    while [ ! -d "$directory" ]
    do
        directory=$(dirname $directory)
    done

    #if the first existing parent directory is not writable by user then create it and its nonexistent parent directories
    #then open it in editor as root
    if [ ! -w $directory ]
    then
        echo The file does not exists, or not visible for you,
        echo and its directory requires root privileges to write in
        echo Please enter your password to proceed:
        $authenticator dirtouch -f $file -e $editor 
        exit 0
    #if first existent parent directory of wanted file is writable by user then no need for authentication
    else
        echo The file does not exist, creating it...
        dirtouch -f $file -e $editor 
        exit 0
    fi
}

#if file does not exists then create it
if [ ! -f $file ]; then touchfile; fi

#if user has no right to edit the file then ask for it
if [ ! -w $file ]; then auth; fi

#if file exists and is writable by user, just edit it 
$editor $file
